//
//  ProgramTableViewController.swift
//  collegeCompass
//
//  Created by Apple on 6/12/19.
//  Copyright © 2019 Apple. All rights reserved.
//

import UIKit

var myIndex = 0
struct Headline {
    
    var id : Int
    var title : String
    var text : String
    var URL: String
}

var headlines = [
    Headline (id: 1 , title:  "BOLD@OLIN" , text:  "Join other young women for a week of engaged discovery at Olin Business School. BOLD@Olin is WashU's summer program for rising junior and senior high school women interested in business. During the week-long program students will be immersed in life-changing opportunities for learning, networking, and personal growth. Students will learn from Olin Business School faculty; network and be inspired by accomplished women in business; and engage in opportunities to develop their leadership potential." , URL:  "https://olinwustl.campusgroups.com/bsba/bold@olin/" ),
    Headline (id: 2 , title:  "Olin Fleischer Scholars Program" , text:  "How would you like to learn about business and entrepreneurship from one of the top business schools in the country? The Olin Fleischer Scholars Program provides a unique, week-long educational experience for high school students entering your sophomore, junior, or senior year. This program is designed to help students with limited financial resources, those from underrepresented populations, and first-generation college students prepare for college and career planning." , URL:  "https://olinwustl.campusgroups.com/bsba/bold@olin/" ),
    Headline (id: 3 , title:  "WashU High School Summer Scholars Program" , text:  "Enroll in undergraduate courses for credit and study alongside undergraduates. Select from a broad range of stimulating introductory courses in humanities, math, sciences, and social sciences. Live on campus in one of our top-ranked residence halls and enjoy social and cultural opportunities with other students from around the world. This program is open to current sophomores and juniors in high school" , URL:  "http://summerexperiences.wustl.edu" ),
    Headline (id: 4 , title:  "WashU High School Summer Institutes" , text:  "Institutes combine traditional undergraduate class and lab curriculum with organized field trips, guest lectures, and hands-on activities in order for students to gain valuable academic and career experience. These programs are open to current freshmen, sophomores, and juniors in high school." , URL:  "http://summerexperiences.wustl.edu" ),
    Headline (id: 5 , title:  "WashU Architecture Discovery Program" , text:  "The Architecture Discovery Program (ADP) is an exciting introduction to architecture and design for high school students. Our rigorous two-week program offers intensive individual instruction by Sam Fox School faculty. The explorations carried out in studio will provide students with quality material to add to their design portfolios. This program is recommended for rising juniors and seniors in high school. Upon successful completion, participants will earn two college credits and may receive letters of recommendation for college admission." , URL:  "https://samfoxschool.wustl.edu/precollege" ),
    Headline (id: 6 , title:  "WashU Portfolio Plus Program" , text:  "Get a taste of what life is like on a college campus while studying art this summer through Portfolio Plus. Open to high school students, this three-week program features drawing courses in the mornings and electives in the afternoons. Studio work is rounded out by organized trips to museums, visits to artists' and designers' studios, and portfolio development workshops. This program is recommended for rising juniors and seniors in high school. Upon successful completion, participants will earn three college credits and may receive letters of recommendation for college admission." , URL:  "https://samfoxschool.wustl.edu/precollege" ),
    Headline (id: 7 , title:  "Northwestern National High School Institute (Cherubs)" , text:  "NHSI has five divisions: Debate, Speech, Journalism, Film & Video Production, and Theater Arts. Students gain practical college-level experience in their chosen field; interact closely with outstanding faculty; tackle new social and intellectual challenges; and experience campus life with other exceptional high school students." , URL:  "http://nhsi.northwestern.edu" ),
    Headline (id: 8 , title:  "Medill-Northwestern Journalism Institute" , text:  "This in-depth, five-week program is designed for students who have just finished their junior year of high school and wish to become better writers and editors for print, online and broadcast. Enrollment is limited to 84 and students typically come from as many as 25 states and abroad. Teachers are top-notch practitioners and distinguished Northwestern faculty." , URL:  "http://cherubs.medill.northwestern.edu/2018/" ),
    Headline (id: 9 , title:  "The Center for Talent Development" , text:  "CTD offers enrichment programs for academically talented students from PreK through grade 12, facilitating high achievement, self-confidence and a love of learning among participants." , URL:  "https://www.ctd.northwestern.edu/2019-center-talent-development-summer-programs-northwestern-university" ),
    Headline (id: 10 , title:  "Northwestern College Preparation Program" , text:  "Explore the world-class city of Chicago and experience college life at Northwestern University this summer. High school sophomores and juniors enroll in undergraduate courses for college credit or a two-week IN FOCUS seminar in a special topic area." , URL:  "https://sps.northwestern.edu/college-preparation/index.php" ),
    Headline (id: 11 , title:  "EducationUSA Academy" , text:  "This unique academic program will provide instruction in English, college preparatory content, tours of diverse college and university campuses, and cross-cultural activities for 15- to 17-year-old students from around the world." , URL:  "https://sps.northwestern.edu/pre-college/education-usa/index.php" ),
    Headline (id: 12 , title:  "Northwestern College Bridge Program" , text:  "25 juniors from Chicago Public School high schools enroll in courses as part of the Northwestern Summer Session and students earn college credit for satisfactorily completed courses." , URL:  "https://sps.northwestern.edu/pre-college/college-bridge/index.php" ),
    Headline (id: 13 , title:  "Northwestern Pathways" , text:  "Learn what makes UChicago one of the most innovative and impactful universities in the world through the Pathway programs. Explore different facets of a subject area, in order to learn more about the approaches and issues involved, and to determine which facet they want to study further." , URL:  "https://summer.uchicago.edu/programs/pathways" ),
    Headline (id: 14 , title:  "UChicago Summer Immersion Programs" , text:  "Whether it’s the remote depths of the universe or this planet’s great works of literature, we know that everybody is passionate about something. This summer, take advantage of the rich educational resources offered by the University of Chicago and transform your passion into your expertise." , URL:  "https://summer.uchicago.edu/programs/immersion" ),
    Headline (id: 15 , title:  "UChicago Summer College" , text:  "Join us this summer to explore new subjects, delve into a current interest with intense focus, and broaden your powers of perception while earning college credit for undergraduate courses at the University of Chicago.As a Summer Session student, you have the opportunity to enroll in undergraduate courses drawn from the regular curriculum of the College at the University of Chicago." , URL:  "https://summer.uchicago.edu/programs/summer-college" ),
    Headline (id: 16 , title:  "Research in the Biological Sciences (RIBS)" , text:  "Furthering the diagnosis and treatment of cancer, discovering how to preserve blood, laying the mathematical foundations for the theory of genetic evolution—the University of Chicago Biological Sciences Division is a leader in these and many other areas of research. This summer, learn the techniques used in leading-edge biological research in lab facilities at a premier research university." , URL:  "https://summer.uchicago.edu/programs/research-biological-sciences-ribs" ),
    Headline (id: 17 , title:  "UIUC Girls' Astronomy Summer Camp" , text:  "This summer camp for high school girls will be focused on hands-on astronomy projects. Join this 2-day summer camp to play with real astronomical data and hang with UIUC professors and graduate students! Build a Mars rover with LEGO, watch 3D science movies in the NCSA visualization lab, work on Hubble data in campus computer labs, observation sessions at the University of Illinois observatory (a historical landmark), and talk to UIUC astrophysicists about their research." , URL:  "https://engage.illinois.edu/entry/38240" ),
    Headline (id: 18 , title:  "UIUC Environmental Engineering and Sustainability Camp (Women-Focused)" , text:  "The Environmental Engineering and Sustainability camp focuses on designing sustainable technological solutions for critical environmental and energy challenges of the 21st Century. Through a series of team activities, lab exercises, and field trips, campers have the opportunity to learn about research and careers in civil and environmental engineering. " , URL:  "https://engage.illinois.edu/entry/37294" ),
    Headline (id: 19 , title:  "UIUC Discover Engineering Camp" , text:  "Discover Engineering (DE) is a week-long, residential camp for rising freshmen and sophomores with a strong interest in math and science. Campers work on several projects that incorporate different aspects of engineering. Campers will visit various research labs around campus, become familiar with the different forms of engineering disciplines studied at Illinois, and interact directly with faculty and students actively researching in these areas. This is a great way to gain a better understanding of engineering in general, as well as an increased understanding of the wide range of careers and areas of study available for engineers." , URL:  "https://engage.illinois.edu/entry/37278" ),
    Headline (id: 20 , title:  "UIUC Discover Bioengineering Camp" , text:  "Discover Bioengineering is a week-long residential camp that introduces rising freshman and sophomores to the field of Bioengineering. Bioengineering includes modeling of systems, designing new technologies and devices, and improving healthcare. Bioengineers study and understand how complex biological systems work,  design and construct medical devices and therapeutics, and solve  healthcare problems facing society." , URL:  "https://engage.illinois.edu/entry/37283" ),
    Headline (id: 21 , title:  "Illinois Aerospace Institute Summer Camp" , text:  "The Illinois Aerospace Institute (IAI) summer camp is a one-week residential program for students entering grades 9-12 who are interested in learning about the fields of aerospace engineering and aviation. Though most of the students who attend are from the Midwest, students come to us from all over the U.S. and internationally. Many campers have some sort of experience with the aerospace field, through model rockets, remote control airplanes, or having a family member who is a pilot, but no experience is necessary, just an interest in learning about the field of aerospace engineering. The Institute is held on the campus of the University of Illinois at Urbana-Champaign. Students stay at in a University or University-certified residence hall with live-in camp counselors. Students will learn about a variety of topics regarding aerospace engineering through classroom sessions, laboratories, demonstrations, and hands-on activities." , URL:  "https://engage.illinois.edu/entry/37514" ),
    Headline (id: 22 , title:  "UIUC Summer Piano Institute" , text:  "The Summer Piano Institute at the University of Illinois offers advanced study for young pianists. Participants will benefit from individual lessons with each SPI faculty member, attendance at daily master classes and access to newly renovated practice rooms all equipped with Steinway grand pianos. Included with the program are performance opportunities and admission to faculty recitals. For 2019, we are pleased to continue the concerto competition available to all participants for the opportunity to compete for a performance with Sinfonia da Camera, the resident professional orchestra of Krannert Center for the Performing Arts, University of Illinois." , URL:  "http://publish.illinois.edu/summerpiano/" ),
    Headline (id: 23 , title:  "UIUC Mechanical Science & Engineering Camp (Women-Focused)" , text:  "Mechanical Engineering is all about building things! Mechanical engineers understand how machines work and how to design and construct new ones to solve challenging problems in the world. Campers will get hands-on experience building and designing machines that make the world a better place, using all their creativity and problem-solving skills. The camp will also include field trips to on-site labs and nearby research and manufacturing companies." , URL:  "https://engage.illinois.edu/entry/37293" ),
    Headline (id: 24 , title:  "UIUC Exploring the Intersection of Creativity and Engineering Camp" , text:  "This camp will explore design, creativity, and innovation in engineering through hands-on projects and team activities. These projects will engage the campers in brainstorming, ideation, synthesis, and prototyping." , URL:  "https://engage.illinois.edu/entry/37280" ),
    Headline (id: 25 , title:  "UIUC Chemical Engineering Camp (Women-Focused)" , text:  "Chemical engineering combines science and mathematics to produce useful materials. In most cases, a chemical engineer takes a scientific process or discovery and engineers it so that it can be made on a large scale. By making food, clothes, power, medicines, and plastic on a large scale, they are then more affordable for all of us!" , URL:  "https://engage.illinois.edu/entry/37292" ),
    Headline (id: 26 , title:  "UIUC Sports & Entertainment Media Camp" , text:  "Personalize your on-campus experience with classes and workshops that interest you the most in the fields of journalism, advertising or media and cinema studies. Learn from faculty and pros in the field." , URL:  "https://engage.illinois.edu/entry/37561" ),
    Headline (id: 27 , title:  "UIUC Exploring Education Summer Camp" , text:  "Join the College of Education on the Illinois Campus for a 5 day, 4 night camp to explore innovative teaching methods, advanced education technology, and global learning. This camp is designed for high school students who are considering a career in education. Come explore your interests with us! Campers will have the opportunity to stay and dine in campus housing, experiment with cutting-edge educational technology, connect with k-12 students around the world via skype sessions, and discuss education practice and global learning with Illinois graduate students and faculty." , URL:  "https://engage.illinois.edu/entry/37123" ),
    Headline (id: 28 , title:  "ACES Research Apprentice Program" , text:  "The University of Illinois at Urbana-Champaign - College of Agricultural, Consumer and Environmental Sciences (ACES) is pleased to invite applications from current high school sophomores and juniors of under-served, economically disadvantaged groups, and urban residents to participate in the Research Apprentice Program. Students invited to participate will be required to pay a $50.00 participation fee.  Upon completion of the program students may qualify for a monetary award. " , URL:  "https://engage.illinois.edu/entry/37727" ),
    Headline (id: 29 , title:  "USDA Ag Discovery Program" , text:  "Learn about career possibilities in the plant, animal and veterinary sciences, and learn how the USDA protects the American food supply.  Over four weeks, students will live on the University of Illinois campus and have hands-on experiences in animal and plant laboratories, conducting small laboratory exercises under supervision of plant and animal scientists, and veterinarians, employed by the University and USDA.  Field trips will be to USDA facilities, agricultural businesses, conservation areas, and zoological facilities to experience the vast aspects of the food and agriculture system. Students enhance academic skills in math, science and computers.  Selected students will also have the opportunity to participate in a two week S.T.E.M. education series of workshops in advance of Ag Discovery sponsored through the Research Apprentice program. " , URL:  "https://engage.illinois.edu/entry/37726" ),
    Headline (id: 30 , title:  "UIUC Discover Architecture Pre-College Program" , text:  "Discover Architecture is a two-week, residential, pre-college program offered by the Illinois School of Architecture at the University of Illinois at Urbana Champaign.  The purpose of the program is to introduce high-school students and recent graduates to the discipline of architecture both as a profession and as a field of academic endeavor.  Students will learn about architectural drawing, physical modeling, freehand sketching, and other tools of the architectural trade.  Upon completion, each student leaves not only with this knowledge, but with drawings and photographs to form the basis of his/her portfolio." , URL:  "https://engage.illinois.edu/entry/37720" ),
    Headline (id: 31 , title:  "Illinois Gies College of Business Emerging Business Leaders Program" , text:  "The Emerging Business Leaders (EBL) program at Gies College of Business is a two-week summer program designed for high-achieving Black, African-American, Hispanic, Latina/o, and Native American students entering their senior year of high school. Participants live on campus and learn from world-renowned faculty, work on a capstone group project with other students, and connect with corporate executives to expand their knowledge on business-related careers." , URL:  "https://engage.illinois.edu/entry/37732" ),
    Headline (id: 32 , title:  "UIUC Robotics Camp (Women-Focused)" , text:  "Robotics Camp gives young women the opportunity to harness the power of computer technology and bring a robotic creation to life by building, programming, and controlling autonomous robots. Campers will participate in stimulating computer labs, hands-on robotic development and computer programming using the LEGO Mindstorm NXT system, Zumo robot by Pololu, and other activities that focus on group problem solving and creativity to address issues facing society today." , URL:  "https://engage.illinois.edu/entry/37291" ),
    Headline (id: 33 , title:  "UIUC Materials Science & Engineering Camp (Women-Focused)" , text:  "Everything is made of materials. From buildings to batteries, clothing to cars, we depend on materials for many things in our everyday life. Materials science and engineering (MatSE) is all about understanding the structure and properties of materials ranging from the atomic scale to the macro-scale.  Then we learn how to process them to get desired performance in new and existing technologies.  Advancements in our understanding of materials will enable next generation technologies for power generation and storage, transportation, sustainable packaging of foods and consumer goods, biomedical applications, and many, many others! Materials science and engineering is a highly collaborative, interdisciplinary field.  If you like math, physics, chemistry and engineering but can’t choose between them—MatSE is the perfect place for you explore all of these fields under one umbrella.  Campers will explore this diversity through hands-on activities including guided lab activities aimed at introducing key concepts in MatSE and the opportunity to design a prototype based on materials properties that your team discovers."  , URL:  "https://engage.illinois.edu/entry/37290" ),
    Headline (id: 34 , title:  "UIUC Exploring Mechanical Science & Engineering Camp" , text:  "Mechanical Engineering is all about building things! Mechanical engineers understand how machines work and how to design and construct new ones to solve challenging problems in the world. This camp will explore many of the exciting new topics in mechanical engineering. Campers will get hands-on experience building and designing machines that make the world a better place, using all their creativity and problem-solving skills. The camp will also include field trips to on-site labs and nearby research and manufacturing companies." , URL:  "https://engage.illinois.edu/entry/37282" ),
    Headline (id: 35 , title:  "UIUC Aerospace Engineering Camp (Women-Focused)" , text:  "From tiny airplanes delivering packages to sending humans to Mars, today is an exciting time for everything related to Aerospace Engineering!  This camp provides young women with the opportunity to explore aerospace engineering through numerous hands-on projects and demonstrations. Utilizing individual and team activities, participants will investigate various aspects of this discipline comprising flight mechanics, aerodynamics, aerospace structures, orbital mechanics, and propulsion systems to then apply them to aircraft and spacecraft design." , URL:  "https://engage.illinois.edu/entry/37289" ),
    Headline (id: 36 , title:  "UIUC Illini Summer Academy - Veterinary Medicine" , text:  "Are you interested in animals, medicine, and science? Do you like helping people? Do you like unraveling mysteries? Do you like real challenges? If you answered yes to these questions, then the wide world of veterinary medicine just may be for you. Veterinarians have a strong interest and ability in science. They enjoy working with people as well as with animals. Take a step into the world of veterinary medicine and see what veterinary school is like, learn about the different aspects of veterinary medicine, and more. Participants in the veterinary medicine academy will learn about the science of veterinary medicine, anatomy, immunology, bacteriology, parasitology, wildlife medicine, large and small animal medicine, and more. Participants will participate in clinical equine rounds, streak and read bacteriology slides, learn about veterinary specialty fields and so much more. Youth must have completed 10th grade prior to the conference." , URL:  "https://engage.illinois.edu/entry/38149" ),
    Headline (id: 37 , title:  "Illinois Aerospace Institute Summer Camp" , text:  "The Illinois Aerospace Institute (IAI) summer camp is a one-week residential program for students entering grades 9-12 who are interested in learning about the fields of aerospace engineering and aviation. Though most of the students who attend are from the Midwest, students come to us from all over the U.S. and internationally. Many campers have some sort of experience with the aerospace field, through model rockets, remote control airplanes, or having a family member who is a pilot, but no experience is necessary, just an interest in learning about the field of aerospace engineering. The Institute is held on the campus of the University of Illinois at Urbana-Champaign. Students stay at in a University or University-certified residence hall with live-in camp counselors. Students will learn about a variety of topics regarding aerospace engineering through classroom sessions, laboratories, demonstrations, and hands-on activities." , URL:  "https://engage.illinois.edu/entry/37513" ),
    Headline (id: 38 , title:  "iSTEAM Summer Program" , text:  "In this intriguing hands-on program, students will form mock firms to collaborate and solve problems in environmental science, architectural engineering, and design technology. By working on projects and taking campus excursions, you will strengthen your abilities and gain knowledge about professional fields of study." , URL:  "https://engage.illinois.edu/entry/37723" ),
    Headline (id: 39 , title:  "UIUC Fine + Applied Arts (FAA) Summer Intensive" , text:  "At this immersive, weeklong program, each high school student selects one major and one minor. Current FAA faculty members, graduate students, and recent FAA graduates teach classes Monday through Friday. Participants also join in evening activities such as bowling, ice skating, sand volleyball, shopping on campus, swimming, scavenger hunts, and trips to Krannert Art Museum. The FAA Summer Intensive concludes with an open house showcasing all work for families and participants." , URL:  "http://faa.illinois.edu/future-students/faa-summer-intensive" ),
    Headline (id: 40 , title:  "UIUC Exploring Nuclear, Plasma, & Radiological Engineering Camp" , text:  "Campers will explore nuclear, plasma and radiological engineering disciplines through many hands-on projects and demonstrations. Through individual and team activities, participants will investigate the disciplines of nuclear energy, plasma and fusion technologies, and radiological science." , URL:  "https://wyse.engineering.illinois.edu/summer%E2%80%90camps/exploring-npre/#sthash.CWszhBfp.SPlBkB0N.dpbs" ),
    Headline (id: 41 , title:  "UIUC Bioengineering Camp (Women-Focused)" , text:  "Bioengineers study and understand how complex biological systems work and how to design and construct medical devices, better therapeutics, and solutions to large health and wellness problems facing society today. This camp focuses on the technical while also considering the societal impacts on current issues of healthcare, health disparities, and sustainability." , URL:  "https://wyse.engineering.illinois.edu/summer%E2%80%90camps/bioengineering-women/#sthash.TVBIiFAM.UQLSYINB.dpbs" ),
    Headline (id: 42 , title:  "ResearcHStart Program for High School Students" , text:  "ResearcHStart welcomes high school students from the Chicago and Urbana-Champaign areas to explore exciting careers in cancer research. Participants work full time in the laboratories of established cancer researchers, gaining hands-on experience in areas at the forefront of the field: cancer immunology, pharmacogenomics of anticancer agents, bioengineering, experimental cancer therapeutics, cancer disparities, and more. Rigorous research training is complemented by career development and skill-building workshops, a cancer-based faculty lecture series, and a network of faculty and peer mentors dedicated to students’ success. The program culminates in a research symposium for family, friends, and members of the scientific community." , URL:  "https://cancer.uchicago.edu/education/pipeline-programs/researchstart/" ),
    Headline (id: 43 , title:  "Summer Illinois Math (SIM) Camp Delta" , text:  "Summer Illinois Math (SIM) Camp is a week-long math day camp for middle and high school students hosted by the University of Illinois at Urbana-Champaign Department of Mathematics. Campers will see the creative, discovery driven side of mathematics. By showing them some of the ways mathematicians approach problems, SIM Camp hopes to encourage them to continue studying math beyond the high school level." , URL:  "https://math.illinois.edu/illinois-geometry-lab/summer-illinois-mathematics-camp" ),
    Headline (id: 44 , title:  "UIUC Electrical Engineering Camp (Women-Focused)" , text:  "The Girls Learning Electrical Engineering (GLEE) camp for high school women explores the depth and breadth of Electrical and Computer Engineering. Campers learn how research in this discipline benefits society as a whole. The technical program includes classroom instruction, demonstrations, hands-on activities, tours, usage of research facilities, and four team projects. The curriculum showcases practical applications of ECE (circuits, signals, electromagnetics, power, nanotechnology, solid state electronics, and photonics) by investigating a real world technology – the cell phone." , URL:  "https://wyse.engineering.illinois.edu/summer%E2%80%90camps/electrical-engineering-women/#sthash.RX9phRlF.yz3cuU8h.dpbs" ),
    Headline (id: 45 , title:  "Telluride Association Summer Program" , text:  "A Telluride Association Summer Program (TASP) is a free six-week educational experience for high school juniors that offers challenges and rewards rarely encountered in secondary school or even college. Each program is designed to bring together young people from around the world who share a passion for learning." , URL:  "https://www.tellurideassociation.org/our-programs/high-school-students/summer-program-juniors-tasp/" ),
    Headline (id: 46 , title:  "Research Science Institute (RSI)" , text:  "RSI is the first cost-free to students, summer science & engineering program to combine on-campus course work in scientific theory with off-campus work in science and technology research. Open to all grades except 12th grade. Students strong in STEM are encouraged to apply. Students invited to the six week long program receive free tuition, room, and board. The only expense is transportation to and from MIT." , URL:  "https://www.cee.org/research-science-institute" ),
    Headline (id: 47 , title:  "Secondary Student Training Program (SSTP)" , text:  "A five-and-a-half-week residential program for gifted 10th and 11th graders at the University of Iowa. Students spend about 40 hours per week in a laboratory setting conducting scientific research under the guidance of a faculty mentor. Financial aid available." , URL:  "http://www2.education.uiowa.edu/belinblank/students/program.aspx?P=SSTP&utm_campaign=coschedule&utm_source=twitter&utm_medium=belinblank" ),
    Headline (id: 48 , title:  "Wharton Leadership in the Business World" , text:  "Affords rising high school seniors the possibility to explore business at the Wharton School in the University of Pennsylvania, widely considered as one of the premier business schools in the world. After a competitive application process, students will work in small groups, take classes with Wharton faculty, and collaborate in small groups to simulate real business practices. Need-based financial aid is available as well. Application opens in mid-November." , URL:  "https://www.wharton.upenn.edu/leadership-business-world/" ),
    Headline (id: 49 , title:  "California State Summer School for Mathematics and Science (COSMOS)" , text:  "The California State Summer School for Mathematics and Science (COSMOS) is a summer program for high school students in California for the purpose of preparing them for careers in mathematics and sciences. It is often abbreviated COSMOS. The program is hosted on four different campuses of the University of California, at Davis, Irvine, San Diego, and Santa Cruz. The mission of COSMOS is to motivate the most creative minds of the new generation of prospective scientists, engineers and mathematicians who will become leaders for California, the nation, and the world. The program aims to create a community of students who participate in and contribute to an intensive academic experience delivered by distinguished educators and scholars. Please check a COSMOS website for more detailed information on the application process and eligibility. Financial aid is available to CA students, for up to $2600 of the $3570 tuition, however students from across the US are invited to apply." , URL:  "https://cosmos-ucop.ucdavis.edu/app/main" ),
    Headline (id: 50 , title:  "Yale Young Global Scholars" , text:  "A two week leadership-development program for high school students from around the world. Choose between six intensive, interdisciplinary summer pre-collegiate experiences: Politics, Law, and Economics; International Affairs and Security; Sustainable Development and Social Entrepreneurship; Applied Science and Engineering; Biological and Biomedical Science; and Frontiers of Math and Science. Financial aid is available to students with demonstrated financial need." , URL:  "https://globalscholars.yale.edu" ),
    Headline (id: 51 , title:  "Young Writers' Studio" , text:  "A summer, residential, creative writing program for high school students that wish to advance their knowledge of distilling ideas and visions into language. Students choose a single Core Course of Study (Poetry, Fiction, or Creative Writing) as a focus for two weeks of the program. The program costs $2,350; however, financial aid is offered as well." , URL:  "https://iyws.clas.uiowa.edu" ),
    Headline (id: 52 , title:  "Notre Dame Leadership Seminars" , text:  "Notre Dame Leadership Seminars, an all expenses paid, college-credit granting program for high school juniors, explores topics affecting the global community. The courses are centered around vibrant discussion and a robust exchange of ideas. This creates a context in which students are encouraged to examine their own conclusions and hone their own leadership capacities by improving their communications and analytical skills. Expenses for students accepted to Leadership Seminars, including transportation to and from Notre Dame, will be paid for by the University. Required fees for the Notre Dame Leadership Seminars include a non-refundable $52.25 application fee to be submitted at the time of application and a $150 non-refundable enrollment fee to be submitted at the time of acceptance into the program. Application fee waivers are granted rarely and only in extreme circumstances. Approximately 100 students are admitted to Leadership Seminars each year, and students are eligible to receive one college credit upon completion of the program. Interested students must submit an online application, a high school transcript, SAT, ACT, or PSAT scores, a counselor report, and a letter of recommendation from a high school teacher. Please refer to the website to learn more about the eligibility and application requirements. The application deadline is January 30th. All applicants will be notified of decisions around the middle of March." , URL:  "https://precollege.nd.edu/leadership-seminars/" ),
    Headline (id: 53 , title:  "Henry Clay Center for Statesmanship High School Student Congress" , text:  "This free week-long Student Congress gathers fifty college or high school students together with lawmakers, academics, journalists, and business leaders to discuss the importance of applying the art of compromise in every aspect of their activities. Carefully selected guest speakers engage with the students throughout the week." , URL:  "http://henryclaycenter.org/high-school-student-congress/" ),
    Headline (id: 54 , title:  "MIT Launch" , text:  "Selective four-week entrepreneurship program and start up incubator aimed at providing a collaborative environment where high school students can study and apply their passions towards creating initiatives or organizations. Students take classes with MIT faculty, work in small groups, and conduct final pitches to business leaders. Need based financial aid is available. Two sessions are available, in June and July." , URL:  "https://launchx.com/summer-program/massachusetts-institute-of-technology" ),
    Headline (id: 55 , title:  "NRECA Youth Tour" , text:  "The Electrical Cooperative Youth Tour brings state delegations of high school students to Washington, D.C., for one week in June to learn about the political process, see American history up close, and meet their U.S. Representatives and Senators. The Youth Tour culminates on Youth Day, where all 1500 students come together. In addition, one student from each state delegation is chosen to serve on the NRECA?s Youth Leadership Council (YLC). Members of the YLC meet with NRECA leaders and Youth Tour alumni in addition to delivering a speech to their peers. Expenses for travel, meals, and housing are all covered as part of the program." , URL:  "https://www.electric.coop/our-organization/youth-programs/" ),
    Headline (id: 56 , title:  "The Kenyon Review Young Writers Workshop" , text:  "An intensive two-week workshop for high school students who wish to develop creative and critical abilities with language. For more than nineteen years, Young Writers has provided a lively, supportive environment for students to challenge themselves as writers and thinkers. Students will also have the opportunity to engage with a community of talented writers and create a network that lasts long after the program has ended." , URL:  "https://www.kenyonreview.org/workshops/young-writers/" ),
    Headline (id: 57 , title:  "CATALYST Academy" , text:  "Cornell's CATALYST Academy seeks to bolster diversity in engineering by providing access to STEM for minority (African American, Latinx, Native American/Alaskan Native, or Pacific islander) and first-generation students. CATALYST students participate in field sessions, research/design projects, and social activities. Rising seniors in the specified minority groups may be eligible to attend free if they meet specified minimum requirements. Financial aid is also granted based on demonstrated need." , URL:  "https://sites.coecis.cornell.edu/catalystacademy/" ),
    Headline (id: 58 , title:  "Summer Math and Science Honors Academy (SMASH)" , text:  "SMASH is a five-week, three-year STEM enrichment summer program for underrepresented high school students (African American, Latino/a, Native American, Southeast Asian or Pacific Islander, low-income, first-in-family to attend college) in eligible counties of California and Georgia. SMASH students develop critical thinking, civic awareness, leadership and sense of social responsibility. Students also engage in SAT prep, college counseling, and financial aid workshops. Applicants must be high school freshmen and attend private high school via scholarship or public high school. The application consists of the SMASH math assessment, an essay, two letters of recommendation, income verification, 8th grade transcript, and standardized test math scores." , URL:  "https://www.smash.org/programs/smash-academy/" ),
    Headline (id: 59 , title:  "Google's Computer Science Summer Institute (CSSI)" , text:  "A three week introduction to computer science for graduating high school seniors with a passion for technology, especially students from historically underrepresented groups. Attend the program at one of eight Google office locations and experience Google's unique culture and innovation firsthand. Residential and Day Camps available. Scholarships are available." , URL:  "https://buildyourfuture.withgoogle.com/programs/computer-science-summer-institute/#!?detail-content-tabby_activeEl=overview" ),
    Headline (id: 60 , title:  "The Science Summer Program" , text:  "SSP is an immersion into experimental science, designed to challenge and inspire talented rising seniors from around the world. Working in teams of three, participants complete a research project from beginning to end: either in Astrophysics at CU Boulder or New Mexico Tech (near-earth asteroid imaging and orbit determination), or Biochemistry at Purdue (fungal enzyme inhibition and drug discovery). Each team acquires its own original data and performs its own analysis. Field trips and guest speakers round out an intense 39-day schedule. The acceptance rate is approximately 10 percent. The program fee of approximately $5,450 is all-inclusive except for transportation, covering room & board, tuition, and all supplies for 39 days and nights. If the fee is more than your family can afford, don?t be discouraged. It is free to apply, admission decisions are need-blind, and SSP awards generous financial aid up to the full program fee plus $500 airfare. If you attend school in the U.S., your parent may wait to see whether you will be admitted before applying for financial aid. (International applicants must apply for aid by the application deadline.) About 40% of participants receive financial aid, including some who attend for free. SSP can commit to making their program affordable for every admitted applicant regardless of family income." , URL:  "https://summerscience.org" ),
    Headline (id: 61 , title:  "Neubauer Family Adelante Summer Scholars" , text:  "Neubauer Family Adelante Summer Scholars provides the opportunity for Hispanic and Latinx students who are rising seniors to study select courses in writing or science at the University of Chicago Summer Session. Summer Scholars attend free of charge including travel. Summer Scholars study in the morning and explore Chicago in the evenings. Students with an outstanding commitment to the Hispanic and Latinx community are encouraged to apply. The application requires letters of recommendation (students are encouraged to give recommenders information on the course/program they are pursuing in advance), short essays to pre-written prompts to show who you are beyond grades, and an analytical writing sample." , URL:  "https://summer.uchicago.edu/programs/neubauer-family-adelante-summer-scholars" ),
    Headline (id: 62 , title:  "Stanford University Mathematics Camp" , text:  "A summer camp that focuses on pure mathematical enrichment for students interested in developing a more fundamental base in mathematics. Students are exposed to research projects and work in groups, giving presentations on certain math topics to peers and allowing them to build a strong network with like-minded individuals." , URL:  "http://sumac.stanford.edu" ),
    Headline (id: 63 , title:  "Alpha Young Writers Workshop" , text:  "A 11-day program for young writers (ages 14-19) who are interested in science fiction, fantasy, and horror. Students will learn about writing and publishing, talk about short stories and films, write an original piece, and learn from professional authors. Workshop tuition is $1,200 and includes housing and meals; however, a small pool of financial aid is offered to those who cannot otherwise attend the workshop." , URL:  "https://alpha.spellcaster.org" ),
    Headline (id: 64 , title:  "Canada/USA Mathcamp" , text:  "Canada/USA Mathcamp is an intensive five-week-long summer program for mathematically talented high school students, designed to expose these students to the beauty of advanced mathematical ideas and to new ways of thinking. At Mathcamp, students can explore undergraduate and even graduate-level topics while building problem-solving skills that will help them in any field they choose to study." , URL:  "https://www.mathcamp.org" ),
    Headline (id: 65 , title:  "UCSB Research Mentorship Program" , text:  "The Research Mentorship Program is a competitive, six-week summer program (end of June to beginning of August) that engages qualified, high-achieving high school students from all over the world in interdisciplinary, hands-on, university-level research. Both STEM and humanities topics are available. Students will be paired up with a mentor (graduate student, postdoc, or faculty) and choose a research project from a large list of disciplines offered by the program each year. In addition to gaining a deep relationship with their mentor, they will learn about research techniques, gain insight into professional research-based opportunities, and mature their academic goals. The lecture series - GRIT talks - will connect students to some of the best minds among the UCSB research community who present on their ground-breaking research and innovative technology. Along with these academic benefits, the students will be immersed in university life and networked with equally ambitious and curious peers. Please view the website for eligibility and financial information. A limited number of full and partial scholarships are available and are awarded based on financial need, academic merit, and availability. Out-of-state and international applicants are eligible for scholarships; however, priority is given to California residents. At least a 3.8 GPA is required, and sophomores and juniors are eligible to participate. Rolling admission from mid-December through mid-March." , URL:  "https://www.summer.ucsb.edu/pre-college/research-mentorship-program-rmp" ),
    Headline (id: 66 , title:  "Girls Who Code" , text:  "Girls Who Code was founded with a single mission: to close the gender gap in technology. The summer program is a free seven-week summer programs for current 10th-11th grade girls to learn coding and get exposure to tech jobs. Transportation stipends are also available." , URL:  "https://girlswhocode.com/summer-immersion-programs/" ),
    Headline (id: 67 , title:  "UC Davis Young Scholars Program" , text:  "A summer residential research program that exposes 40 high school students to the world of natural sciences research with emphases on the biological, environmental, and agricultural sciences. Students must currently be enrolled as sophomores or juniors in high schools, and will work one-on-one with research faculty and groups in laboratories for six weeks on an individual project, along with a journal quality paper and symposium presentation." , URL:  "https://ysp.ucdavis.edu" ),
    Headline (id: 68 , title:  "Princeton University Summer Journalism Program" , text:  "Located at Princeton University, this summer program offers 35-40 rising high school seniors from low-income backgrounds an opportunity to engage in an intensive, 10-day seminar on journalism. Classes are taught by reporters and editors from reputable news outlets and cover a range of topics from sports to investigative journalism. All expenses, including travel to and from Princeton, are paid for by the program." , URL:  "https://psjp.princeton.edu" ),
    Headline (id: 69 , title:  "Awesomemath Summer Program" , text:  "An intensive summer math experience for gifted and enthusiastic middle and high school students. Rigorous math instruction with an emphasis on collaborative problem solving, balanced with fun camp activities that allow participants to connect on a different level. Both residential and day options. Scholarships and limited financial aid available. Discount available for early application. January 20 to apply early or March 31 to apply regular." , URL: "https://www.awesomemath.org/summer-program/overview/program-information/" ),
    Headline (id: 70 , title:  "Young Women's Institute" , text:  "The Young Women's Institute introduces young women who are juniors in high school to college and business by providing them with the opportunity to interact with Indiana University Kelley School of Business female students, alumni, and faculty. The Young Women's Institute includes attending workshops, preparing real-word business case projects, and building leadership and communication skills. The program is free excluding travel and personal expenses." , URL:  "https://kelley.iu.edu/programs/undergrad/pre-college/ywi.cshtml" ),
    Headline (id: 71 , title:  "Program in Mathematics for Young Scientists (PROMYS)" , text:  "PROMYS is a top-tier, challenging six-week residential program at Boston University that engages students in the creativity of mathematics. Students participate in mathematical discovery to solve an assortment of unusually challenging problems in Number Theory, all the while getting access to visiting scientists and research mathematicians. PROMYS resident counselors are recent high school graduates and undergraduates students from institutions such as Harvard, MIT, and Princeton. Returning PROMYS students may participate in advanced seminars and original research under faculty. Full and partial need-based financial aid are available in addition to a very small number of merit scholarships. The instructional fee is automatically waived for students with family incomes less than $60,000. Applicants must be 15 years of age by the first day of the program and are judged based on their solutions to a set of challenging problems, teacher recommendation, high school transcript, and responses regarding interest in the program." , URL:  "https://promys.org" ),
    Headline (id: 72 , title:  "Ross Mathematics Program" , text:  "Six-week summer mathematics experience for ambitious high school students (ages 15-18) at Ohio State University. Teaches students to think critically and appreciate abstract concepts, as they deeply focus on a single subject throughout the experience. Scholarship support available" , URL:  "https://rossprogram.org" ),
    Headline (id: 73 , title:  "UCLA SciArt Nanolab Summer Institute" , text:  "The UCLA SciArt NanoLab Summer Institute of a highly competitive two-week program for high school juniors and seniors interested in collaborating with diverse and notable minds to intertwine artistic and scientific approaches to nanotechnology in a way that addresses challenges from a completely novel standpoint." , URL:  "https://www.summer.ucla.edu/institutes/SciArtNanoLab" ),
    Headline (id: 74 , title:  "Benjamin Franklin Transatlantic Fellows Summer Institute" , text:  "The Benjamin Franklin Transatlantic Fellowship (or BFTF for short) is a unique and exciting program initiated and funded by the U.S. Department of State, and hosted by Wake Forest University. As you enjoy your stay in the U.S. and explore American culture and politics you will learn about the opportunities and challenges of civil society. You will gain insight and the knowledge that, combined with your own experiences, will equip you well for leadership and activist roles. During the program you will have a chance to interact with over 45 other students from over 30 countries in Western Europe, Eastern Europe, Eurasia and the U.S. For ten days you will be staying at the home of an American family, which will provide you with a great opportunity to experience American culture up-close. There will be classes and dialogues around certain topics as well as several small group intensive projects and exciting trips to several great locations, including Washington DC and Philadelphia, PA. This program is for students aged 16-18 only. An application for United States citizens is available on the website, due mid-April. If you are from one of the other participating nations, please contact the United States embassy in your nation for information about the application process." , URL:  "https://de.usembassy.gov/education/benjamin-franklin-transatlantic-fellows-initiative/" ),
     Headline (id: 75 , title:  "US Naval Academy Summer STEM program" , text:  "Five day program located at the US Naval Academy in Maryland for high school students interested in pursuing careers in science, technology, engineering, and math. This hands-on program will help students explore STEM career paths while making new friends. Limited financial aid is available, although transportation costs are not covered." , URL:  "https://www.usna.edu/Admissions/Programs/STEM.php" ),
     Headline (id: 76 , title:  "Chapman University Summer Economics Program" , text:  "This series of workshops for high school students introduce students to Experimental Economics, attract potential economics majors, and identify promising individuals for internships and pre- and post-doctoral fellowships. At the end of June, IFREE and Thomas W. Smith Foundation sponsors this one week-long workshop on experimental economics for rising junior and senior students. For those rising seniors who might not have the opportunity to study economics in their high schools, the objective of these workshops is to expose them to and get them interested in the foundations of economic analysis using experimental economics. A subset of the students may have already taken economics classes, and for those students, the goal is to cultivate their interest in economics and introduce them to economics as an observational science with new topics, problems, and experiments. This workshop does not assume any previous study in economics. Please note, the workshop will be an all commuter program. Students that are able to commute to and from the workshop are welcome to apply. Students are responsible for their transportation commuting to and from the workshop each day. Out of state students can apply to the program if the students arrange their own lodging/accommodations and transportation. The deadline for students to submit applications and for teachers to submit teacher recommendation forms is typically at the end of the first week of April." , URL:  "https://www.chapman.edu/research/institutes-and-centers/economic-science-institute/conferences-and-workshops/summer-scholars.aspx" ),
     Headline (id: 77 , title:  "Gakko Project" , text:  "Gakko brings together teams of driven individuals to design two-week summer camps for high schoolers. At each camp, sempai (the college students facilitating the camp) invite the kohai (high school students) to participate in a given investigation, that allows them to experience the world in a completely unique way. Gakko Camp is built on the philosophy of Kikkake: a Japanese word meaning being the spark for new connections, perspectives, and ideas. Camps are held abroad in France, Romania, Bali, and Japan, and financial aid to cover tuition is available." , URL:  "https://www.gakko.org" ),
     Headline (id: 78 , title:  "Outward Bound" , text:  "Outward Bound is dedicated to a simple mission: exploring the outdoors. These opportunities are offered in various locations around the United States and the world. A range of leadership, backpacking, and nature driven experiences are offered. Outward Bound?s financial aid typically covers between 10 to 30 percent of the total tuition." , URL:  "https://www.outwardbound.org" ),
     Headline (id: 79 , title:  "Dartmouth College Bound" , text:  "Program at Dartmouth College that gives students from underrepresented communities a look into life at Dartmouth by immersing them into the college. Students will live in the residence halls and participate in admissions/financial aid workshops, interact with faculty and classes, and connect to other students." , URL:  "https://admissions.dartmouth.edu/visit/visitation-programs/dartmouth-bound-summer-program" ),
     Headline (id: 80 , title:  "Summer College for High School Students (SCHS)" , text:  "Summer College for High School Students (SCHS) is a four-week academic program designed to provide US and international rising junior and senior high school students between the ages of 15 and 17 years old the opportunity to have a glimpse of college life for four weeks during the summer. As part of the program, students take two college-level classes in one of several fields, gaining college credits for each, having the opportunity to see how collegiate level classes are structured, and what college professors expect from them. Financial aid is available based on ACT scores (27+). Limited need-based aid is available. Those who receive above a 27 are eligible for merit-based aid, and those who score above a 33 or 1440 on the SAT have the entire program fee covered. See the website for more information. The application deadline for Session I is May 1st, and the application deadline for Session II is June 1st. Just remember that once the session fills up, the application process closes. To guarantee your spot, apply early." , URL:  "http://www.outreach.olemiss.edu/schs/index.html" ),
     Headline (id: 81 , title:  "Adroit Summer Mentorship Program" , text:  "An entirely free and online program that pairs experienced writers with high school and secondary students (as of the current academic year) interested in learning more about the creative writing processes of drafting, redrafting and editing. Alumni have been recognized through various prestigious organization ranging from YoungArts to Presidential Scholars to the National Scholastic Art and Writing Awards. Students may also submit their work up until August 15th." , URL:  "https://theadroitjournal.org/about/mentorship/" ),
     Headline (id: 82 , title:  "Brandeis Service Corps" , text:  "The Brandeis Service Corps is an immersive, hands-on experience in community service for high school students who want to change the world. Participants engage in volunteer projects related to various areas of social justice and even design their own project in an area of their passion, all the while experiencing college life at a top-tier university. Students can gain up to 45 hours of community service credit by completing the program. Limited scholarships are available for outstanding students and need based financial aid is available for qualifying students on a first-come, first-served basis." , URL:  "https://www.brandeis.edu/precollege/service-corps/index.html" ),
     Headline (id: 83 , title:  "CalArts Summer Program" , text:  "A studio environment in which students can devote attention to creative talents for free. CalArts provides assistance through faculty, alumni, and other students to help build professional portfolios, culminating in the documentation of your work. You must live in Los Angeles County to be eligible for this program." , URL:  "https://calarts.edu/discover-calarts-program" ),
    Headline (id: 84, title: "Kode with Klossy", text: "Kode with Klossy’s flagship program provides the opportunity for young women across the country, ages 13-18, to attend free two week bootcamps that introduce them to key computer science concepts and skills. Scholars collaborate with each other and with inspiring instructors to explore the limitless potential of code and computer science.", URL: "https://www.kodewithklossy.com")
]

class ProgramTableViewController: UITableViewController {
    
    @IBOutlet weak var menuTableView: UITableView!
    
   
    
  /*  override func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    } */

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return headlines.count
    }

    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "LabelCell", for: indexPath)
        cell.textLabel?.text = headlines[indexPath.row].title
        return cell
    }
    
    override func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        return "Summer Programs"
    }
    

    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        
        myIndex = indexPath.row
        self.performSegue(withIdentifier: "segue", sender: self)
    }
}
